project:
  group: laplacian
  name: template.project-template
  type: template
  namespace: laplacian
  version: '1.0.0'
  description:
    en: |
      The template-project-template project.
    ja: |
      The template-project-template project.
    zh: |
      The template-project-template project.
  module_repositories:
    local:
      ../../../mvn-repo
    remote:
    - https://github.com/nabla-squared/mvn-repo
  template_files:
  - 'dest/template'
